# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/CC.ico"

[footer]
since = 2023
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
# emoji = "ğŸ¥"
# compact = true
subtitle = "Let life be beautiful like summer flowers."

# å¤´åƒè®¾ç½®
[sidebar.avatar]
enabled = true
local = true
src = "img/CC.jpg"

# æ•°å­¦æ”¯æŒ KaTex
[article]
math = true
readingTime = true
toc = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

# å³è¾¹çš„å¯¼èˆªæ ï¼Œå±•ç¤ºåˆ†ç±»ï¼Œæ ‡ç­¾ç­‰ç­‰
## home ç•Œé¢å¯¼èˆªæ 
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

## æ­£æ–‡ç•Œé¢å¯¼èˆªæ 
[[widgets.page]]
type = "toc"  # æ­£æ–‡å¤§çº²

# åˆ†äº«åˆ°Twitterï¼Œå¯¹å›½å†…ç”¨æˆ·åŸºæœ¬æ²¡ç”¨
[opengraph.twitter]
site = ""
card = ""

# å¦‚æœé¡µé¢æ²¡æœ‰æŒ‡å®šå°é¢çš„è¯ï¼Œåˆ™é»˜è®¤ä½¿ç”¨è¯¥å›¾ç‰‡
[defaultImage.opengraph]
enabled = false
local = false
src = ""  # æŒ‡å®šnordèƒŒæ™¯ä¸ºé»˜è®¤å°é¢

# è‡ªåŠ¨å¤œé—´/æ—¥é—´æ¨¡å¼
[colorScheme]
toggle = true
default = "auto"

# resizeé¡¹ç›®ä¸­çš„å›¾ç‰‡
[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments  è®¾ç½®disqusè¯„è®ºåŠŸèƒ½
[comments]
enabled = false
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
